# - Key Setup -

# The port which you defined in your proxy config.
server-port: 8000

# The IP of your proxy.
server-host: "0.0.0.0"

# The port which this client (this Spigot server) will bind to, so it can listen for the proxy.
client-port: 8001

# The IP this client will bind to.
# This should usually be left as 0.0.0.0, or 127.0.0.1, but feel free to change this if you need to -
# (i.e. you are on shared hosting / Pterodactyl)
client-host: "0.0.0.0"

# - Options -

# How many milliseconds it will wait for a connection.
# A timeout will be pronounced if the server does not respond in this time.
connection-timeout: 2000

# Time in milliseconds that Skript will wait from a response from the proxy in each, condition, effect and expression.
# Decreasing this will improve overall performance, but make sure this doesn't go below the ping between the client and the proxy -
# as it will drop the packet!
packet-response-time: 1000


# This will toggle the display of detailed messages about what is going to the console.
# When filing a bug report / checking for issues, this is extremely useful to know what exactly went wrong!
debug: false