name: ZulfBungee
main: tk.zulfengaming.zulfbungee.spigot.ZulfBungeeSpigot
version: 0.6.88
author: zulfen
website: https://github.com/Zulfen/ZulfBungee
description: A Skript addon which adds Bungeecord / Proxy intergration to your server!
depend: [Skript]